name       : python-pyrsistent
version    : 0.16.0
release    : 3
source     :
    - https://pypi.python.org/packages/source/p/pyrsistent/pyrsistent-0.16.0.tar.gz : 28669905fe725965daa16184933676547c5bb40a5153055a8dee2a4bd7933ad3
license    : MIT
component  : programming.python
summary    : Persistent/Immutable/Functional data structures for Python
description: |
    Pyrsistent is a number of persistent collections (by some referred to as functional data structures). Persistent in the sense that they are immutable.
builddeps  :
    - pkgconfig(python3)
    - python-hypothesis
    - pytest-runner
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
