name       : python-pyrsistent
version    : 0.18.0
release    : 6
source     :
    - https://pypi.python.org/packages/source/p/pyrsistent/pyrsistent-0.18.0.tar.gz : 773c781216f8c2900b42a7b638d5b517bb134ae1acbebe4d1e8f1f41ea60eb4b
license    : MIT
component  : programming.python
summary    : Persistent/Immutable/Functional data structures for Python
description: |
    Pyrsistent is a number of persistent collections (by some referred to as functional data structures). Persistent in the sense that they are immutable.
builddeps  :
    - pkgconfig(python3)
    - python-hypothesis
    - pytest-runner
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
